export const GAME_CONFIG = {
  match: {
    durationSeconds: 300,
    tickRateHz: 30,
    simulationSpeed: 0.6,
    defaultSeed: "vivatech-grid-duel-demo",
  },
  demand: {
    baseTotalMW: 140,
    progressionSteps: 6,
    progressionStartSeconds: 40,
    progressionEndSeconds: 270,
    progressionJitterSeconds: 10,
    sectors: {
      householdsMW: [80, 100, 120],
      businessMW: [15, 35, 55],
      dataCentersMW: [45, 65, 85],
    },
  },
  market: {
    minPrice: 70,
    maxPrice: 120,
    priceElasticity: 2.2,
    minMargin: 0.3,
    maxMargin: 1,
    moneyScale: 0.001,
    maxShareChangePerSecond: 0.012,
    minShare: 0.1,
    maxShare: 0.9,
  },
  players: {
    startingCash: 80,
    startingSubscribedLoadShare: 0.5,
    startingScore: 0,
    startingStrikes: 0,
  },
  assets: {
    gridCapacityMW: 210,
    plantLevels: {
      nuclearMW: [35, 70, 105],
      thermalMW: [45, 70, 95],
      renewablePeakMW: [25, 40, 55],
      waterDamStorageMWh: [20, 35, 50],
      waterDamPowerMW: [15, 25, 35],
    },
    nuclear: {
      capacityMW: 35,
      rampMWPerSecond: 15,
      initialOutputMW: 35,
    },
    thermal: {
      capacityMW: 45,
      initialThrottle: 0.38,
      heatGainPerSecond: 0.07,
      coolingPerSecond: 0.04,
      overheatThreshold: 0.85,
      outputMultiplierWhenOverheated: 0.85,
    },
    renewable: {
      solarPeakMW: 10,
      solarShare: 0.4,
      solarDefaultFactor: 0.75,
      solarCloudFactor: 0.3,
      windPeakMW: 15,
      windShare: 0.6,
      windCutInKmh: 12,
      windFullPowerKmh: 45,
      windCutOutKmh: 90,
      windDefaultKmh: 35,
    },
    waterDam: {
      capacityMWh: 20,
      maxPowerMW: 15,
      initialStoredRatio: 0.5,
      fillEfficiency: 0.75,
      drainEfficiency: 0.9,
      storageSecondsPerMWh: 20,
      rainFillMWhPerSecond: 0.5,
      rainAutoDrainThreshold: 0.95,
    },
  },
  efficiency: {
    targetUtilizationMin: 0.85,
    targetUtilizationMax: 0.98,
    edgeUtilizationMax: 1,
    overContractedMax: 1.05,
  },
  breaker: {
    safeBalanceBand: 0.05,
    severeBalanceMismatch: 0.15,
    balanceBreakerSeconds: 3,
    severeBalanceTimerMultiplier: 3,
    balanceRecoverySeconds: 1,
    capacityOverloadInstantThreshold: 1.05,
    capacityOverloadBreakerSeconds: 3,
    capacityOverloadRecoverySeconds: 1,
    breakerTripSeconds: 8,
    gridShutdownReliefSeconds: 15,
    resetCost: 35,
  },
  strike: {
    cashPenalty: 25,
    subscriberLossRatio: 0.1,
    scorePenalty: 80,
  },
  upgrades: {
    repeatCostMultiplier: 1.25,
    renewable: {
      baseCost: 45,
      buildSeconds: 10,
    },
    thermal: {
      baseCost: 40,
      buildSeconds: 8,
    },
    nuclear: {
      baseCost: 85,
      buildSeconds: 20,
    },
    waterDam: {
      baseCost: 50,
      buildSeconds: 12,
    },
  },
  contracts: {
    business: {
      loadMW: 15,
      durationSeconds: 45,
      completionCashReward: 35,
      strikeScorePenalty: 70,
    },
    dataCenter: {
      loadMW: 25,
      durationSeconds: 35,
      completionCashReward: 60,
      strikeScorePenalty: 140,
    },
  },
  cards: {
    cloudFront: {
      cost: 30,
      cooldownSeconds: 25,
      warningSeconds: 2,
      durationSeconds: 8,
      opponentRenewableSolarFactorMultiplier: 0.65,
    },
    windStorm: {
      cost: 30,
      cooldownSeconds: 25,
      warningSeconds: 2,
      durationSeconds: 8,
      opponentWindKmh: 100,
    },
  },
} as const;

export const PLAYER_IDS = ["player", "rival"] as const;
